import { NextResponse } from "next/server";

export async function POST(request: Request) {
  let title = "";

  try {
    const { title: certTitle, provider, type } = await request.json();
    title = certTitle;

    const DEEPSEEK_API_KEY = process.env.DEEPSEEK_API_KEY;

    if (!DEEPSEEK_API_KEY) {
      return NextResponse.json({
        cheatsheet: `# ${title} - Study Notes

## 📌 Quick Overview
[Brief description of what this certification covers]

## 📚 Key Terms & Concepts to Remember
- **Term 1:** Brief definition
- **Term 2:** Brief definition
- **Term 3:** Brief definition

## 🔑 Important Concepts

### Concept 1
**Simple Explanation:** [Easy to understand explanation]

**Analogy:** [Everyday comparison]

**Example:**
\`\`\`
Example code or configuration
\`\`\`

**When to Use:** [Real-world scenario]

---
*Generated by AI. Edit and add your own notes.*`,
      });
    }

    const response = await fetch(
      "https://api.deepseek.com/v1/chat/completions",
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${DEEPSEEK_API_KEY}`,
        },
        body: JSON.stringify({
          model: "deepseek-chat",
          messages: [
            {
              role: "system",
              content: `You are an expert technical tutor. Create a clear, easy-to-understand cheatsheet for the given certification or course.

The cheatsheet must include:
1. A "Key Terms & Concepts to Remember" section with important vocabulary and their brief definitions
2. Detailed explanations of the most important concepts with analogies and examples
3. Explain to me like i'm 12 years old. Use simple language and relatable analogies.
Structure your response EXACTLY like this:

# [Certification Name] - Study Notes

## 📌 Quick Overview
[2-3 sentences about what this certification covers]

## 📚 Key Terms & Concepts to Remember

| Term | Definition |
|------|------------|
| **Term 1** | Brief, clear definition |
| **Term 2** | Brief, clear definition |
| **Term 3** | Brief, clear definition |

(Include 8-12 important terms as a markdown table)

## 🔑 Important Concepts

### 1. [Concept Name]

**Simple Explanation:** [Clear, beginner-friendly explanation]

**Analogy:** [Relatable everyday comparison]

**Example:**
\`\`\`
[Practical example]
\`\`\`

**When to Use:** [Specific real-world scenario]

### 2. [Next Concept]
[Same structure]

DO NOT include exam tips. Focus only on understanding the concepts and key terminology.`,
            },
            {
              role: "user",
              content: `Create a detailed cheatsheet for: ${title} (Provider: ${provider || "Self-paced"}, Type: ${type || "certification"}). Include a "Key Terms & Concepts to Remember" section with important vocabulary, then explain the main concepts with analogies and examples. No exam tips.`,
            },
          ],
          temperature: 0.7,
          max_tokens: 2200,
        }),
      },
    );

    const data = await response.json();
    const cheatsheet =
      data.choices?.[0]?.message?.content ||
      `# ${title} - Study Notes

## 📚 Key Terms & Concepts to Remember

| Term | Definition |
|------|------------|
| **Core Concept** | Understanding the fundamentals |
| **Best Practice** | Recommended approach |

## 🔑 Main Concepts

Add your own notes here.`;

    return NextResponse.json({ cheatsheet });
  } catch (error) {
    console.error("AI cheatsheet generation failed:", error);
    return NextResponse.json(
      {
        cheatsheet: `# ${title || "Certification"} - Study Notes

## 📚 Key Terms & Concepts to Remember

Start by listing the important terms for this certification as you learn them.

| Term | Definition |
|------|------------|
| | |
| | |

## 🔑 Key Concepts

Add your own notes specific to this certification.

---
*AI generation temporarily unavailable. Please add your own notes.*`,
      },
      { status: 200 },
    );
  }
}
